### ISSUE TITLE
Improve build efficiency via support for pod anti-affinity 

### ISSUE THREAD

**Issue by chendo** [buildkite/charts#102]
**Is this a request for help?**: No

---

**FEATURE REQUEST?**:

Support for pod anti-affinity rules.

We deploy multiple instances of this chart into our CI cluster, however occasionally we run into issues where one node is loaded more than others, due to an uneven distribution of pods. This can sometimes be rectified by redeploying the Deployment, but ideally we would be able to specify anti-affinity rules. We would likely preferentially distribute based on hostname where possible in our setup.

Ideally, we would have it automatically reschedule pods if agents aren't being used and there is capacity, although this probably requires a custom scheduler which would be more complicated.

Another aspect of this problem is the Buildkite scheduler would ideally consider the node an agent is running on, but that's outside the scope of the Helm chart.

We are currently on Kubernetes 1.20.x.

**Comment by triarius** [comment]
Hi @chendo, unfortunately we've stopped active development on this project. There's a newer, fully supported way to run buildkite-agent on k8s in [github.com/buildkite/agent-stack-k8s](github.com/buildkite/agent-stack-k8s). You should be able to specify anti-affinity rules in the Buildkite Pipeline YAML for your steps through it.

You're more than welcome to contribute PRs to this repo, however.

**Comment by chendo** [comment]
@triarius I see. I've not had a chance to play with agent-stack-k8s just yet, but it doesn't seem to have anything out of the box that address the efficiency issues. If a Job is being created for every step, wouldn't it need to:

* Checkout from git from scratch
* Boot a fresh DIND instance
* Pull all the images on a fresh DIND instance (or build from scratch)
* Run the step

This seems rather inefficient. I suspect it would be doable to shoehorn in some kind of improvements, but I feel like the agent-stack should have built-in primitives to help with this stuff.

**Comment by triarius** [comment]
That's a good call out. The approach we took in agent-stack-k8s is that building container images is a service that will have to be provided by some other means, and then maintaining a build cache is the responsibility of that service. But it's up to the user on what to choose for that, we don't want to make this a primitive for Buildkite Pipeline YAML as we think different users would want to take different approaches, including ones that don't involve docker at all.
