### ISSUE TITLE
Integration with TravisCI is not working 

### ISSUE THREAD

**Issue by rimusz** [buildkite/charts#24]
@toolmantim can you take a look to it, I do not have permissions to change integration settings

**Comment by rimusz** [comment]
fixed it by using CircleCI for charts testing and GCP Cloud Build of releasing chart to gh-pages

**Comment by toolmantim** [comment]
Nice! Can you give me access to the GCP Cloud Build?

**Comment by toolmantim** [comment]
Not really necessary! Out of interest, how’d you end up at using two diff services?

**Comment by rimusz** [comment]
circleci is set only for PRs from main repo and forks, cloud build (using my private, as you get 2 hours free per day) is set to master only.

**Comment by rimusz** [comment]
@toolmantim if you want I can show you around via zoom how all works there
