### ISSUE TITLE
how is the GCP service key used?

### ISSUE THREAD

**Issue by nhooyr** [buildkite/charts#38]
This is a question.

I noticed that the service key provided as a value to the chart is put into `/etc/service_key`.

From here, is it automatically used by`kubectl`, `helm` and `gcloud`?

**Comment by rimusz** [comment]
GCP service account is needed if you want to access private GCR registry

**Comment by nhooyr** [comment]
Yes I understand that but how is passed to `kubctl`, `helm` et all? Like in the code. How does `kubectl` know the key is in` /etc/service_key`?

**Comment by rimusz** [comment]
the service account file (which can push to registry, deploy to kubernetes and etc)  `gcr_service_account.key` gets amounted to: `/etc/service_key` folder.
The in your Buildkite pipeline you can use it as:
```
export GOOGLE_APPLICATION_CREDENTIALS=/etc/service_key/gcr_service_account.key
``` 
then kubectl, gcloud and will work for you.

**Comment by nhooyr** [comment]
Awesome, thanks for clarifying.
