### ISSUE TITLE
Make mounting docker socket optional

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/charts#39]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Mounting in the docker socket from the host is quite a large security risk to accept, especially if deploying this chart in a critical cluster like a production cluster. I'd like to make this feature configurable, with a default of enabled for backwards compatibility (if desired) so that the risk can be mitigated for users who wish.  
An example use case is running a fleet of Buildkite agents on vanilla hosts (eg using the [EC2 CloudFormation template](https://github.com/buildkite/elastic-ci-stack-for-aws)) which have access to docker for building and pushing to a registry (and can also keep warm caches). Then using a fleet of agents deployed directly into a Kubernetes cluster which use images from the previous fleet to deploy apps. The agents running inside the cluster don't need access to docker since that is done in a previous step and hence would benefit from closing off the risk of mounting the hosts docker socket.

**Version of Helm and Kubernetes**: n/a

**Which chart**: agent

**What happened**: mounts host docker socket by default

**What you expected to happen**: optionally mount host docker socket

**How to reproduce it** (as minimally and precisely as possible): apply the chart as-is

**Anything else we need to know**: I'm willing to make a PR if you would accept such a change :smile:

**Comment by rimusz** [comment]
hey, thanks for opening the issue, sure the PR would be very welcome!

**Comment by jradtilbrook** [comment]
Hello again. Upon further inspection, I'm wondering whether the pods `securityContext` should also be removed if the `enableHostDocker` is false?
Eg: https://github.com/buildkite/charts/blob/master/stable/agent/templates/deployment.yaml#L39

**Comment by rimusz** [comment]
it should be made optional, I will make a PR in a few next days

**Comment by jradtilbrook** [comment]
I don't mind doing another PR for this and I'll probably be able to get to it tomorrow if you like. Do you think it should be wrapped into the same flag from the original PR: `enableHostDocker`?

Full transparency, I don't quite understand the purpose but it seems linked to security stuff related to the host, which was half the point of that flag.
However, to support backwards compatibility it's probably best if its a separate variable.

Let me know, I'm happy to help if you want it

**Comment by rimusz** [comment]
PR would be welcome, you could similar to these
https://github.com/jfrog/charts/blob/master/stable/kubexray/values.yaml#L61
https://github.com/jfrog/charts/blob/master/stable/kubexray/templates/deployment.yaml#L34
