### ISSUE TITLE
Remove unnecessary RBAC permissions from chart

### ISSUE THREAD

**Issue by geekflyer** [buildkite/charts#41]
When enabling rbac the chart grants a lot of permissions to the buildkite agent: https://github.com/buildkite/charts/blob/master/stable/agent/templates/clusterrole.yaml

What are those permissions used for by the agent? I didn't see any mention of RBAC in the official docs and I'm wondering if this is even necessary? Does the buildkite agent ever call kubernetes APIs?

**Comment by rimusz** [comment]
everybody has different needs, there is an option to disable the `RBAC` support https://github.com/buildkite/charts/blob/master/stable/agent/values.yaml#L86

**Comment by geekflyer** [comment]
I'm aware that I can disable RBAC support. My question is what the buildkite agent uses those permissons for if RBAC is enabled? 
I'm not aware of buildkite natively supporting / using any k8s API so I'm wondering what's the point of granting those permissions.

**Comment by rimusz** [comment]
not, it is not using k8s API yet

**Comment by geekflyer** [comment]
Ok thanks for the clarification.
I think the permissions should be removed from the chart then until they're actually needed if ever.
I'll update the issue title accordingly.

**Comment by rimusz** [comment]
It makes more sense to have RBAC disabled by default

**Comment by rimusz** [comment]
RBAC got disabled by default in chart v0.3.8
