### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by scottrobertson** [buildkite/charts#43]
Hey

Getting the following when i install the helm package?

```
NAME:   bk-agent
LAST DEPLOYED: Sat May 11 19:31:49 2019
NAMESPACE: buildkite
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                TYPE    DATA  AGE
bk-agent-buildkite  Opaque  2     0s

==> v1/ServiceAccount
NAME                SECRETS  AGE
bk-agent-buildkite  1        0s

==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
bk-agent-buildkite  4        0        0           0          0s


NOTES:
#### THIS CHART IS DEPRECATED! ####
```

Is this deprecated? Should I be installing/running this in a different way?

**Comment by rimusz** [comment]
you must using chart from https://github.com/helm/charts/tree/master/stable/buildkite which is of course depreciated in favor in the chart in `https://github.com/buildkite/charts/tree/master/stable/agent`
You need run:
https://github.com/buildkite/charts#add-buildkite-helm-chart-repository
then install chart:
https://github.com/buildkite/charts/tree/master/stable/agent

**Comment by scottrobertson** [comment]
@rimusz perfect, thank you. I somehow missed that it changed from `stable/buildkite` to `buildkite/agent`.
