### ISSUE TITLE
Support Pod annotations

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/charts#46]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

Add support to add extra annotations on the pod. The specific use case I am after is to support [kiam](https://github.com/uswitch/kiam) so the pod that is deployed can access some AWS resources. Eg for pulling config or secrets to perform a deploy of an app.	

I think this could be added just like the `extraEnv` value.

This would be used instead of a Buildkite agent hook that exported raw IAM credentials.

**Comment by rimusz** [comment]
done in #48
