### ISSUE TITLE
make gh-pages branch to work as Helm v2 repo

### ISSUE THREAD

**Issue by rimusz** [buildkite/charts#9]

**Comment by rimusz** [comment]
had no luck to make it work, closing it, will push to helm charts upstream instead

**Comment by bendrucker** [comment]
Did you end up pushing this to another repo? Looked around but didn't find it.

**Comment by rimusz** [comment]
it is here in helm charts upstream https://github.com/kubernetes/charts/pull/1797 and also will be in another public new helm repo next week

**Comment by rimusz** [comment]
just clone the git repo and install from there for now

**Comment by bendrucker** [comment]
Sweet, thank you!

**Comment by rimusz** [comment]
will add the urls when chart is alive at both
